[project]
name = "llama-flash"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.9",
    "numpy>=2.3.4",
    "pytest>=8.4.2",
    "tiktoken>=0.12.0",
    "torch>=2.9.0",
    "triton>=3.5.0",
]
